### ISSUE TITLE
请问节点拒绝连接的原因是什么？

### ISSUE THREAD

**Issue by wziye4554** [HuangLab-SYSU/block-emulator#1]
ubuntu@ubuntu-virtual-machine:~/桌面/block-emulator-main$ go run main.go -c -N 4 -S 2 -m 3 
Supervisor: 2023/05/23 10:51:11 supervisor.go:162: Supervisor begins listening：127.0.0.1:18800
2023/05/23 10:51:11 connect error dial tcp 127.0.0.1:8800: connect: connection refused
2023/05/23 10:51:11 connect error dial tcp 127.0.0.1:8900: connect: connection refused

**Comment by ChenQinde** [comment]
出现这个报错，有可能是两个原因之一引起的：

1. 节点的端口被占用，也就是说如 8800、8900 这些端口被其他进程所占用。
2. 节点未启动，也就说如 127.0.0.1:8800 的节点并未上线，这自然也无法进行通讯。

因为提问本身的信息不是很详细，在这里提供一个简单的检查方式：**查看项目下的 log 日志文件夹，是否有对应节点的日志生成**

- 如果节点对应的日志生成了，那么报错的原因可能是上述的第一个原因，也即端口被占用；
- 如果节点对应的日志未生成，那么报错的原因可能是上述的第二个原因，也即节点未启动。

如果是上述的第一个原因，其对应的解决方案如下：

- 1. 采用网络工具，如 netstat，查看机器端口是否空闲。
- 2. 修改 build 文件夹下初始端口的配置，将初始端口设置为机器**空闲的端口**。

如果是上述的第二个原因，其对应的解决方案如下：

- 启动区块链的 worker 节点，详细查看 [BlockEmulator help document](https://github.com/HuangLab-SYSU/block-emulator/blob/main/docs/en/Help%20Documents.md) 中的 3.2 auto start 章节的运行步骤。

希望上述方法能帮助你解决你遇到的问题。

PS：如果上述提供的方法无效，希望能够提供更加详细的问题描述，比如参数的配置、bug 的截图等等。
