### ISSUE TITLE
请问当分片和节点数量过多时，如何正确实现在多台PC上运行代码，我在两台PC上运行时，出现了另一台PC上的所有分片交易数据都是0，应该如何执行？

### ISSUE THREAD

**Issue by wujiaying1** [HuangLab-SYSU/block-emulator#11]

**Comment by iiinotlll** [comment]
你好，感谢你的问题。
这种情况可能是 IP 地址设置出现了问题，导致某台机器的节点未和 Supervisor 进行通信。
Worker 节点的 IP 地址需要在 ./build/build.go 中的  *initConfig* 函数 进行设置。
Supervisor 节点的 IP 地址需要在 ./params/global_config.go 中进行设置。

IP 地址的修改是通过修改 ./params/static.go 中的 IPmap_nodeTable 来生效的。
