### ISSUE TITLE
pow

### ISSUE THREAD

**Issue by Verge-yang** [HuangLab-SYSU/block-emulator#12]
您好！我想请问read me中提到了本平台可以实现pow和pbft两种共识算法，但项目代码中似乎只有pbft一种共识实现方式？多谢指教

**Comment by BigLittleChef** [comment]
你好，本平台是支持pow和pbft两种共识算法的。但PoW共识需要自己完成一下。

**Comment by Verge-yang** [comment]
好的，感谢指教
