### ISSUE TITLE
May I ask what is the reason for this problem? After I ran it once, I changed the parameters and ran it again. Isn't it possible to run the program multiple times, and what if I want to run it multiple times

### ISSUE THREAD

**Issue by justinSongYu** [HuangLab-SYSU/block-emulator#14]
![截屏2023-11-16 09 44 58](https://github.com/HuangLab-SYSU/block-emulator/assets/94221853/adbeaf19-cb9b-4580-a78a-2808b285a045)

**Comment by wujiaying1** [comment]
I think it may be due to the impact of not deleting the previous log files. You can try deleting the log and record folders before running the program.

**Comment by justinSongYu** [comment]
Thank you very much, the issue has been resolved
