### ISSUE TITLE
关于系统网络层

### ISSUE THREAD

**Issue by Sue147** [HuangLab-SYSU/block-emulator#18]
请问blockemulator系统中节点的网络通信是假定的理想通信吗（即没有信号衰减、延迟、丢包、连接中断或其他网络问题）？我查看了GO SDK工具包中的net.go文件，我发现了一些对于网络问题的处理函数，我个人认为blockemulator中的节点的通信是基于TCP/IP协议的非理想状态通信。不知道我理解是否有误。

**Comment by iiinotlll** [comment]
blockEmulator 中的节点使用了golang 的 net 包来实现网络层（TCP/IP 协议）。使用这个包时，程序不可避免地会出现延迟、丢包等问题，这些问题可能源于 TCP 协议本身（比如 TCP 固有的延迟），也可能源于系统运行时的网络情况。

**Comment by Sue147** [comment]
好的谢谢，我理解了。顺便再问个问题，我该如何设置epoch的值啊？我的实验结果里好像一直是epoch0。

**Comment by iiinotlll** [comment]
在 blockEmulator 中，目前只有 CLPA 相关的方法才会对 Epoch 进行修改。因为 CLPA 方法发生于分片区块链系统运行时的 reconfiguration 阶段，CLPA 改变了系统的配置。**不同的 Epoch（Epoch0，Epoch1 ...） 体现出系统配置的改变对系统性能带来的影响。**

**Comment by Sue147** [comment]
我读了BlockEmulator的介绍论文，第五部分中的B提到设置每个Epoch为80秒，C中的实验结果也是在不同Epoch下的TPS，而且C部分与计算出的理论TPS期望值相对比的实验中系统使用的是relay机制和静态分片算法，所以我很好奇这里的多个Epoch是如何设置的？

**Comment by iiinotlll** [comment]
blockEmulator 论文中，你提及的那部分实验中，Epoch 只是简单地每 80s 增加一次，系统并没有进行 CLPA 之类的系统重构行为。
这一部分实验的实现，是通过修改 supervisor 端的统计函数来实现的。
supervisor 端会接受来自 worker 分片的区块，并且通过 .\supervisor\measure 中的统计函数，生成对应的指标。在上述实验的实现中，对于每个 worker 分片，supervisor 每收到来自 10 个来自该 worker 分片的区块，就会在统计时对这些区块的 Epoch 加 1。因为每个区块出块间隔为 8 s，10 个区块就是 80 s，也就是一个 Epoch。

具体实现的话，以测试 TPS 的代码为例（supervisor\measure\measure_avgTPS_relay.go），增加了变量 blockNum_of_shard。
```
type TestModule_avgTPS_Relay struct {
	epochID      int
	excutedTxNum []float64       // record how many excuted txs in a epoch, maybe the cross shard tx will be calculated as a 0.5 tx
	relayTx      map[string]bool // record whether a relayTx or not
	startTime    []time.Time     // record when the epoch starts
	endTime      []time.Time     // record when the epoch ends

	// 10 blocks = 1 epoch,
	// i.e., epochID of shard #{3} = blockNum_of_shard[3] / 10
	blockNum_of_shard []int
}
```

希望这个回答能解决你的问题~

**Comment by Sue147** [comment]
好的，我理解了，非常感谢！
