### ISSUE TITLE
想把跨分片交易设置成无跨分片交易可行吗

### ISSUE THREAD

**Issue by huihao20** [HuangLab-SYSU/block-emulator#19]
想用这个模拟器做个试验  不涉及跨分配交易，想知道可行吗。要怎么做

**Comment by iiinotlll** [comment]
您是否指的是，单分片情况下的实验？即分片数目为 1 ，此时系统中自然也就不存在跨分片交易。
如果是这样的话，那么只需要将分片数目改为 1 就行了。
以 blockEmulator 的操作手册 (https://github.com/HuangLab-SYSU/block-emulator/blob/main/docs/ch/blockEmlator_manual.md )  *自动启动*这一节  的描述，您可以将生成 bat 文件的代码由 
```
go run main.go -g -S 2 -N 4 -m 3
```
改为：
```
go run main.go -g -S 1 -N 4 -m 3
```

然后按照操作手册中的内容，就可以运行一个单分片的系统。
