### ISSUE TITLE
增加一个broker的子账户

### ISSUE THREAD

**Issue by chenning2022** [HuangLab-SYSU/block-emulator#20]
就是一个broker不是在两个分片中都有自己的账户嘛，然后原本这两个分片牵涉到的跨分片交易都可以通过broker变成分片内交易，那能不能让一个broker在三个分片中都有自己的账户，让这三个分片中牵涉到的跨分片交易变成分片内交易呢，如果这样可以的话，我具体应该怎么做呢
![ed5a59976cd29126cf8ae0bba34945d](https://github.com/HuangLab-SYSU/block-emulator/assets/77774055/4617917c-4b86-4927-9513-391867d7c752)

**Comment by yinin6** [comment]
> broker不是在两个分片中都有自己的账户嘛
你好，broker 并不仅仅只是在两个分片维护状态，而是在每个分片都维护一部分状态。

**Comment by chenning2022** [comment]
有点不太懂，我需要再去看下论文吗

**Comment by yinin6** [comment]
> 就是一个broker不是在两个分片中都有自己的账户嘛，

在论文设计中， broker 在所有分片都有自己的账户。

> 能不能让一个broker在三个分片中都有自己的账户

因为所有分片都有，当然三个分片也是有的。

> 有点不太懂，我需要再去看下论文吗

你好，可以再去看看论文中的详细设计。

**Comment by chenning2022** [comment]
broker在所有分片都有自己的账户，意思是每个分片中都有broker账户吗？

一个broker在所有的分片中都有自己的账户吗？

16个分片，1个broker，这1个broker会在16个分片中都有自己的账户吗？
如果是这样的话，分片中的节点能不能都通过这一个broker充当中间商的作用，来极大的减少跨分片交易比率呢？

**Comment by yinin6** [comment]
> broker在所有分片都有自己的账户，意思是每个分片中都有broker账户吗？

是的，broker 的账户状态会被分割到每个分片，每个分片都维护 broker 的状态。

>  一个broker在所有的分片中都有自己的账户吗？

是的。

> 16个分片，1个broker，这1个broker会在16个分片中都有自己的账户吗？

会的。

**Comment by chenning2022** [comment]
谢谢您的解答！  但我还有一点疑惑

就是如果1个broker在16个分片中都有自己的账户，为什么不能通过论文中提到的方法，将这16个分片产生的跨分片交易都通过这一个broker账户来变成分片内交易，这样的话应该就没有跨分片交易了，这在技术中应该是可行的

我在不变动 -N 4  -S 10  -m 0的实验参数下调整了broker的数量为1、3、7，得到的跨分片交易比率结果分别是0.8、0.5、0.29，这是为什么呢？broker是有条件的处理交易吗

**Comment by chenning2022** [comment]
您好，请问可以解答一下吗，问题本身是错误的也可以告知1qaq

**Comment by yinin6** [comment]
你好，感谢您的提问，关于项目的创新改动以及讨论，您可以自行尝试，这里只负责维护代码的使用以及处理bug问题。
