### ISSUE TITLE
请问Broker的地址和broker文件下的数据有什么关系

### ISSUE THREAD

**Issue by dsr666** [HuangLab-SYSU/block-emulator#21]
这个文件里面的数据是怎么生成的

![`Y64$}3}6NNHEZ}94(UXV_S](https://github.com/HuangLab-SYSU/block-emulator/assets/163745224/66a02480-8217-47e9-becf-3549dc6e6d40)

**Comment by yinin6** [comment]
> 这个文件里面的数据是怎么生成的

你好，这个文件里储存是 Broker 账户的地址。

**Comment by yinin6** [comment]
> 就是Broker账户的地址是怎么得来的

这个是自由设置的，可以自己调整文件中的地址。



> 还是说不论数据集怎么变Broker的账户地址都是从这里面选

是的，Broker 账户地址只从这个文件里边选取。

**Comment by dsr666** [comment]
好的，谢谢您的耐心解答
