### ISSUE TITLE
报错：exit status 0xffffffff

### ISSUE THREAD

**Issue by codelinzhz** [HuangLab-SYSU/block-emulator#24]
请问我启动go run main.go -c -N 4 -S 2 -m 3 报错：exit status 0xffffffff这种是什么情况？要怎么解决？

**Comment by iiinotlll** [comment]
抱歉，错误出现在 .\partition\partition_CLPA.go 文件夹中的 160 行，我们使用了 0x7fffffff 来表示 INT_MAX，但是此处多打了一个 f，超出了 32 位的表示上限。这导致了该行代码在某些机器上会报错。

目前我们已经修改了此部分代码为 math.MaxInt。

烦请您下载最新的代码~

**Comment by codelinzhz** [comment]
修改后还是报错：exit status 0xffffffff
