### ISSUE TITLE
交易数据全是0

### ISSUE THREAD

**Issue by UIZorrot** [HuangLab-SYSU/block-emulator#26]
我按照指示下载了最新的数据集，并且使用了20-29的csv，运行之后所有的结果都是0：

Supervisor看起来是正常运行的

Supervisor: 2024/04/24 23:29:50 committee_relay.go:128: received from shard 1 in epoch 0.
Supervisor: 2024/04/24 23:29:50 committee_relay.go:128: received from shard 0 in epoch 0.
Supervisor: 2024/04/24 23:29:55 committee_relay.go:128: received from shard 1 in epoch 0.
Supervisor: 2024/04/24 23:29:55 committee_relay.go:128: received from shard 0 in epoch 0.
Supervisor: 2024/04/24 23:29:56 supervisor.go:130: Supervisor: now sending cstop message to all nodes
Supervisor: 2024/04/24 23:29:56 supervisor.go:136: Supervisor: now Closing
Supervisor: 2024/04/24 23:29:56 supervisor.go:224: Closing...
Supervisor: 2024/04/24 23:29:56 supervisor.go:226: Average_TPS
Supervisor: 2024/04/24 23:29:56 supervisor.go:227: [] -0
Supervisor: 2024/04/24 23:29:56 supervisor.go:226: Transaction_Confirm_Latency
Supervisor: 2024/04/24 23:29:56 supervisor.go:227: [] NaN
Supervisor: 2024/04/24 23:29:56 supervisor.go:226: CrossTransaction_ratio
Supervisor: 2024/04/24 23:29:56 supervisor.go:227: [0 0] NaN
Supervisor: 2024/04/24 23:29:56 supervisor.go:226: Tx_number
Supervisor: 2024/04/24 23:29:56 supervisor.go:227: [] 0
Supervisor: 2024/04/24 23:29:56 supervisor.go:231: Trying to input .csv
Supervisor: 2024/04/24 23:29:56 supervisor.go:275: [] -0
Supervisor: 2024/04/24 23:29:56 supervisor.go:275: [] NaN
Supervisor: 2024/04/24 23:29:56 supervisor.go:275: [0 0] NaN
Supervisor: 2024/04/24 23:29:56 supervisor.go:275: [] 0

您们知道这个问题是什么原因造成的吗？

**Comment by UIZorrot** [comment]
我似乎发现原因了，不能将csv文件放在根目录，不太清楚其他细节。
同时我还发现模拟结果很奇怪

Average_TPS
-0.00000000
CrossTransaction_ratio
0.00000000,0.00000000,NaN
Transaction_Confirm_Latency
NaN
Tx_number
0.00000000

我运行的是默认的windows批处理文件

**Comment by UIZorrot** [comment]
我知道原因了，因为下载的数据必须选择2，就是blocktransaction，这可能是一个坑，因为说明文档里没讲这个问题

**Comment by westbrookyy** [comment]
> 我知道原因了，因为下载的数据必须选择2，就是blocktransaction，这可能是一个坑，因为说明文档里没讲这个问题

选择2是什么意思啊，CLPA共识协议吗

**Comment by UIZorrot** [comment]
不是，就是下载的数据集，需要选择分块2

**Comment by westbrookyy** [comment]
> 不是，就是下载的数据集，需要选择分块2

那我如果不分片，就不能用这个数据集了是吧

**Comment by UIZorrot** [comment]
这是交易数据集，不可能不用吧？

**Comment by westbrookyy** [comment]
我是改了一下pbft的共识流程，然后只有一个分片，运行之后跟你的问题一样，log也一样，全是空的，但是共识流程是没有问题的，运行正常
