### ISSUE TITLE
CLPA_Broker 在分片是S16的时候出现问题

### ISSUE THREAD

**Issue by hcy123422** [HuangLab-SYSU/block-emulator#28]
执行./bat_shardNum=16_NodeNum=4_mod=CLPA_Broker.sh 时会出现panic: Err tx2
goroutine 287 [running]:
log.Panic({0xc003f05a40?, 0xc0005a7c20?, 0x28?})
        /root/go/src/log/log.go:384 +0x65
blockEmulator/consensus_shard/pbft_all.(*CLPAPbftInsideExtraHandleMod_forBroker).HandleinCommit(0xc0003d94e0, 0xc0004df620?)
        /root/autodl-tmp/blockchain/block-emulator/consensus_shard/pbft_all/pbftInside_modCLPABroker.go:111 +0x750
blockEmulator/consensus_shard/pbft_all.(*PbftConsensusNode).handleCommit(0xc0004c8360, {0xc005d5bdae, 0x86, 0x86})
        /root/autodl-tmp/blockchain/block-emulator/consensus_shard/pbft_all/messageHandle.go:193 +0x7a2
blockEmulator/consensus_shard/pbft_all.(*PbftConsensusNode).handleMessage(0xc0004c8360, {0xc005d5bd90, 0xa4, 0xa4})
        /root/autodl-tmp/blockchain/block-emulator/consensus_shard/pbft_all/pbft.go:167 +0x196
blockEmulator/consensus_shard/pbft_all.(*PbftConsensusNode).handleClientRequest(0xc0004c8360, {0xd9ad40?, 0xc0000140f0})
        /root/autodl-tmp/blockchain/block-emulator/consensus_shard/pbft_all/pbft.go:192 +0x289
created by blockEmulator/consensus_shard/pbft_all.(*PbftConsensusNode).TcpListen
        /root/autodl-tmp/blockchain/block-emulator/consensus_shard/pbft_all/pbft.go:215 +0xa7
为什么会这样

**Comment by iiinotlll** [comment]
这个错误发生在 block-emulator/consensus_shard/pbft_all/pbftInside_modCLPABroker.go 的 111 行。原因是判断 broker 相关的交易时出现了问题：一笔交易是 broker交易的后半笔，但是它的收款方并不在该分片内。

出现这个问题的原因可能是：一个 epoch 的 reconfiguration 计时结束后，收款方账户可能需要发生账户迁移（从旧分片迁移到了新分片，这是CLPA 算法导致的），此时 broker 的后半笔交易将会被发送到了该收款方账户所归属的新分片而非旧分片。而您的配置中将 16 个分片放到一台机器执行，这可能导致 reconfiguration 阶段的账户迁移执行较慢，在账户迁移还未结束时，broker 的后半笔交易就已经发送到新的分片，从而引发了错误。 

如果您对代码进行了一些修改，也可能导致 broker 交易发送到了错误的分片。
