### ISSUE TITLE
数据集中的账户地址和节点关系

### ISSUE THREAD

**Issue by dsr666** [HuangLab-SYSU/block-emulator#29]
请问，在global_config.go中设置的分片节点数和数据集中的账户地址是什么关系。数据集中的账户地址是不是也相当于分片中的节点，还是说在一个分片中的节点只有参数设置里的NodesInShard，而数据集中的账户之间的交易全部分配给这些节点处理。

**Comment by iiinotlll** [comment]
你好，“NodesInShard“ 也就是分片节点数，指的是区块链中每个分片的**共识节点**数目。而账户地址，指的是数据集内进行交易的用户账户。
所以账户和共识节点并不能划等号。您理解的第二点是对的，也就是 ”在一个分片中的节点只有参数设置里的NodesInShard，而数据集中的账户之间的交易全部分配给这些节点处理“。

**Comment by dsr666** [comment]
懂了，谢谢您
