### ISSUE TITLE
请问运行时报如下错误是什么原因，应该如何解决？跪求各位大佬指导

### ISSUE THREAD

**Issue by wujiaying1** [HuangLab-SYSU/block-emulator#3]
Supervisor: 2023/07/03 09:11:53 supervisor.go:179: Supervisor begins listening：127.0.0.1:18800
2023/07/03 09:11:53 new int failed
panic: new int failed

goroutine 34 [running]:
log.Panic({0xc0000a3cd8?, 0xc00013c18b?, 0x8?})
        D:/software/programing/go/src/log/log.go:388 +0x65
blockEmulator/supervisor/committee.data2tx({0xc00010e360, 0x12, 0x12?}, 0x0?)
        F:/shard1/block-emulator-tt/supervisor/committee/committee_relay.go:52 +0x168
blockEmulator/supervisor/committee.(*RelayCommitteeModule).TxHandling(0xc0002b2280)
        F:/shard1/block-emulator-tt/supervisor/committee/committee_relay.go:124 +0x35b
blockEmulator/supervisor.(*Supervisor).SupervisorTxHandling(0xc0002cc3f0)
        F:/shard1/block-emulator-tt/supervisor/supervisor.go:132 +0x8f
created by blockEmulator/build.BuildSupervisor
        F:/shard1/block-emulator-tt/build/build.go:55 +0x145
exit status 2

**Comment by iiinotlll** [comment]
谢谢你的问题。首先说一下推荐的解决方案：重新从 xblock 上下载一份数据集。

类似的问题之前也有人提起，下面是那个问题的解释部分：
该问题出现在 golang 大整数库的转换上，即 golang 无法将 .csv 文件数据集中的 “转账金额”转化为大整数（*big.Int）；如果您 print 数据集中的数据，可能会发现“转账金额”这一项是以科学计数法的方式 print 出的（即类似 1.052E+09），而 golang 大整数转化的相关函数无法识别这样的格式。这是可能是导致出现报错的原因。
从我们下载的数据集看来，这种“print结果以科学计数法表示”的情况是较为少见的，可能是您使用电脑上的某些软件在查看.csv文件时对它进行了兼容性修改。

如果没能解决你的问题，可以向我们提供更多具体信息，或者加入 blockEmulator 交流群进行更具体的提问。

**Comment by wujiaying1** [comment]
好的，非常感谢您的回复，我按照您的要求重新重新下载了数据集，但我不知道为什么在运行时生成测试结果文件.csv文件中的数据都是0,以下是我的数据集文件和生成的日志文件，可以辛苦你们帮忙看一下吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuangLab-SYSU/block-emulator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月4日(星期二) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuangLab-SYSU/block-emulator] 请问运行时报如下错误是什么原因，应该如何解决？跪求各位大佬指导 (Issue #3)





 
谢谢你的问题。首先说一下推荐的解决方案：重新从 xblock 上下载一份数据集。
 
类似的问题之前也有人提起，下面是那个问题的解释部分：
 该问题出现在 golang 大整数库的转换上，即 golang 无法将 .csv 文件数据集中的 “转账金额”转化为大整数（*big.Int）；如果您 print 数据集中的数据，可能会发现“转账金额”这一项是以科学计数法的方式 print 出的（即类似 1.052E+09），而 golang 大整数转化的相关函数无法识别这样的格式。这是可能是导致出现报错的原因。
 从我们下载的数据集看来，这种“print结果以科学计数法表示”的情况是较为少见的，可能是您使用电脑上的某些软件在查看.csv文件时对它进行了兼容性修改。
 
如果没能解决你的问题，可以向我们提供更多具体信息，或者加入 blockEmulator 交流群进行更具体的提问。

**Comment by iiinotlll** [comment]
你好，我这边收到的邮件似乎没有附件。
根据你的描述，系统生成了 .csv文件，但数据都是0，这说明系统在不断打包着空区块，因此我们认为交易注入部分可能出现了问题。
我们推测可能是负责下发交易的 Supervisor 节点没有启动或由于某些原因停止了（**比如18800号端口被占用， “转账金额”转化为大整数出现bug 等原因**）停止了。这个推测可以这样加以引证：**检查运行后产生的  ./log/Supervisor.log 文件，如果该文件内容为空，则就是 supervisor 节点启动异常**。

这是 blockEmulator 的使用视频，你可以参考一下：[https://www.bilibili.com/video/BV1go4y177JY/?spm_id_from=333.337.search-card.all.click&vd_source=7931c4c665e24e290abc1ed35102a0b6](url)

按照上述视频，每个节点运行时都有一个对应的窗口（02：44处），此时你可以找到 supervisor 节点对应的窗口，查看它是否报错而终止。
如果还是没能解决你的问题，你可以向我们呈现 supervisor 节点窗口中的报错信息

**Comment by wujiaying1** [comment]
问题已经解决，非常感谢你们团队的耐心指导，谢谢你们
