### ISSUE TITLE
运行broker方法，为什么分片越多交易延迟越高？

### ISSUE THREAD

**Issue by hcy123422** [HuangLab-SYSU/block-emulator#31]
运行broker 方法时global_config设置是一样的，到达率4000，运行2百万条数据，但在8个分片中他的吞吐量为2685，交易延迟为161。但到16个分片中时，吞吐量下降了，而且交易延迟上升了，为什么？按论文来看，吞吐量不是应该上升吗，交易延迟不是应该下降吗？

**Comment by iiinotlll** [comment]
你好，感谢您的提问。根据我们的初步判断，认为原因是交易到达率设定的较低。

比如，存在这样一种情况，某笔交易在 8 分片时并不是一笔跨分片交易，而在 16 分片时成为了跨分片交易。这导致了这一笔交易的在 8 分片情况下的 Latency 高于 16 分片情况下的 Latency。

多分片相比于少分片的优势体现在交易到达率较高，交易在交易池中累积的情况。在这种情况下，多分片的并行处理优势才能体现出来。
