### ISSUE TITLE
Relay模式下，分片数量固定，改变节点数量时，性能不变

### ISSUE THREAD

**Issue by Cjh-li** [HuangLab-SYSU/block-emulator#33]
您好！请问为什么Relay模式下，设置固定数量的分片，改变节点数量时，TPS和延迟变化很小很小呢？

**Comment by iiinotlll** [comment]
您好，感谢您的问题。
在分片区块链中，区块链的分片数目等同于并行数目，固定分片数目，也就固定了系统的并行程度，所以哪怕变化分片内的节点数目，TPS 和延迟也变化较小。一个分片内的节点数目关乎该分片的安全性，换言之，一个分片内节点数目越多，便能够容忍更多恶意节点，相对来说也就越安全。
（在 pbft 中，系统能够容忍的恶意节点的数目为 $f$，其中 $N \geq 3f + 1$）

**Comment by Cjh-li** [comment]
感谢您的回复！
