### ISSUE TITLE
您好，我更改了PBFT的主节点后一直生成空区块，Supervisor节点的log也是空的

### ISSUE THREAD

**Issue by luoruihan1** [HuangLab-SYSU/block-emulator#35]
我添加了一个简单的PBFT主节点选择算法后只有原主节点(Node 0)一直在监听TCP，其他节点一直在生成空区块，请问这是什么原因？

**Comment by iiinotlll** [comment]
感谢您的问题，根据您的问题，我们修改了一些代码。您可以拉取一下最新的代码，并且检查一下您修改的参数是否影响了其他部分再试试。

**Comment by luoruihan1** [comment]
好的 谢谢！
