### ISSUE TITLE
选择共识方法问题

### ISSUE THREAD

**Issue by dwsqr** [HuangLab-SYSU/block-emulator#38]
在参数里面配置ConsensusMethod = 1，选择CLPA算法，为什么执行的是CLPA_Broker
<img width="847" alt="d30a65f5cf511c13a1a56efba9ad27f" src="https://github.com/user-attachments/assets/ba9103ac-4fdc-4162-bb46-687b315816b3">
<img width="627" alt="d210f99f9afa8d3a9b0449689172eed" src="https://github.com/user-attachments/assets/c4da4a94-ab91-46a3-b7e4-00db682dd674">

**Comment by iiinotlll** [comment]
您好，我们现在将参数配置移到了 `./paramsConfig.json` 文件中，您可以在这个文件中更方便地设置参数。

**Comment by dwsqr** [comment]
感谢
