### ISSUE TITLE
Will the block-emulator support smart contracts?

### ISSUE THREAD

**Issue by litrane** [HuangLab-SYSU/block-emulator#4]
Will the block-emulator support smart contracts? EVM component can be added? 

Thanks.

**Comment by iiinotlll** [comment]
Thank you for your questions. 
Due to the complexity of smart contracts and EVM, we are not going to support smart contracts in our blockEmulator v1.0, 
**but we will support them in the blockEmulator v2.0 which will be open-sourced in a few months.**

**Comment by litrane** [comment]
Awesome! Thanks a lot!
