### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by ZhangZZ-GZU** [HuangLab-SYSU/block-emulator#44]
请问一直出现这个问题是哪里出了问题？
![Snipaste_2024-10-30_19-53-03](https://github.com/user-attachments/assets/ec3a7043-c003-40c2-a580-c662444a6c56)

**Comment by ZhangZZ-GZU** [comment]
我将源码下载后按步骤添加了相关依赖后还是启动不了

**Comment by iiinotlll** [comment]
您好，我们目前在 Win11 和 Linux 上针对您的问题进行了测试，没有复现出您提到的问题。您可以尝试运行 ”提前编译好的可执行文件“ `.\blockEmulator_Windows_Precompile.exe` ，看看是否还会出现 exit status 0xffffffff 的报错。

**Comment by ZhangZZ-GZU** [comment]
好的。经过我的测试我认为是go版本的问题，请问您方便告知测试的go版本吗？

**Comment by ZhangZZ-GZU** [comment]
好的，谢谢你的解答。经过我的测试，发现是go版本的问题。现已正常运行。
