### ISSUE TITLE
请问为什么每个分片中的每个节点都创建了一条链呀，我理解的是同一个分片中的所有节点维护一条链，不同分片维护不同链

### ISSUE THREAD

**Issue by wujiaying1** [HuangLab-SYSU/block-emulator#5]
![image](https://github.com/HuangLab-SYSU/block-emulator/assets/48306928/6eb0550b-8d01-4d09-a9dd-8110063bd255)

**Comment by ChenQinde** [comment]
你的理解没有错误，和我们的实现方案也是一致的。

我们目前的实现方案是，同分片每个节点都是维护同一条链，而不是同一个分片每个节点维护不同的链。

产生误解的原因可能是，代码实现是创建了新的一条链，但是实际上每个节点采用的区块头是一致的，可以认为是同一条链在不同节点的副本。

这一点与现实也是相符的，现实中每一个节点都是在不同的物理机上，节点同步链上的数据。

**Comment by wujiaying1** [comment]
好的，明白了，非常感谢你的回答
