### ISSUE TITLE
请问分区出现以下问题是什么原因，30个分片4个节点

### ISSUE THREAD

**Issue by wziye4554** [HuangLab-SYSU/block-emulator#6]
![微信图片_20230712213011](https://github.com/HuangLab-SYSU/block-emulator/assets/103926786/304300de-7599-4928-bb5f-26386b372efa)

**Comment by iiinotlll** [comment]
你好，感谢你的问题。
我们在单台机器上复现了你的实验配置（30分片，clpa 模式），发现确实会出现这种情况。问题的原因在于，单台PC运行（30*4）个 worker 节点和一个 supervisor 节点对设备的负担太大了，此负担包括 CPU 和网络。

因此我们的建议是，将 blockEmulator 下放到多台PC上运行（比如两台PC的情况：0~15号分片的节点均由1号PC运行，16~31号分片的节点由 2 号PC运行，这需要将原先的批处理文件拆分为两部分）。相关的IP地址可能需要重新配置，你可以在 *./build/build.go* 和 *./params/global_config.go* 中修改对应的 IP 地址，以实现 blockEmulator 在多台设备上的部署。

此外，我们改进了TCP的连接方式为*长连接*，使系统不再频繁地创建和关闭 TCP 连接，这可以缓解节点数目过多的情况下，系统套接字溢出的问题（所以可以放心地在多台机器上部署）。

如果你在实现 blockEmulator 在多台设备上的部署时遇到了问题，也欢迎提问~
