### ISSUE TITLE
请问为什么在分片数量、节点数量、数据集及其设定的交易数量都相同的情况下，为什么每次运行得到的shard04.csv中文件得到的交易数量tx 和跨分片交易数量ctx 都不一样？个人理解的是按地址取模划分分片，那么每次分片数量一定的情况下，每个交易被划分到哪个分片的结果是不会变的

### ISSUE THREAD

**Issue by wujiaying1** [HuangLab-SYSU/block-emulator#7]

**Comment by yinin6** [comment]
你好，shard04.csv 中的两个数字 0，4 分别代表分片ID以及分片总数。该文件的作用是记录分片区块链系统中单一分片的交易上链情况（上链交易的数量）。
因为 supervisor 节点负责交易的注入，worker 节点负责交易共识、打包。节点每次启动时间存在偏差就可能导致交易注入情况发生偏差，导致分片中交易池积累的交易存在差异，打包上链的交易数量可能存在偏差，最终导致每次运行得到的文件结果不同。

**Comment by wujiaying1** [comment]
好的，理解了，非常谢谢你的指导
