### ISSUE TITLE
请问如果要将该代码放在linux操作系统的服务器上进行运行，具体应该如何操作

### ISSUE THREAD

**Issue by wujiaying1** [HuangLab-SYSU/block-emulator#8]

**Comment by iiinotlll** [comment]
你好，感谢你对 BlockEmulator 的关注。
如果要将 BlockEmulator 放在 Linux 下运行，你可以考虑 Linux 下的 ***.sh*** 文件类型，配合 ***&*** 指令并发执行命令行的指令。
你可以参照 *./build/tool.go* 中的 *GenerateBatFile* 函数，写一个生成 *.sh*文件的函数，来代替之。进而生成 Linux 的 *.sh* 执行文件。

如果你在生成 *.sh* 文件时遇到了困难，也可以继续提问。
