### ISSUE TITLE
请问遇到了这种错误应该如何解决？

### ISSUE THREAD

**Issue by wujiaying1** [HuangLab-SYSU/block-emulator#9]
![image](https://github.com/HuangLab-SYSU/block-emulator/assets/48306928/63480e38-afb7-4ff1-8ceb-94fdd9f2667e)

**Comment by iiinotlll** [comment]
您好，通过你提供的报错信息，错误应该是出现在调用以太坊的 ethdb 对状态树进行修改 (*GetUpdateStatusTrie*) 的这部分过程。您是否对该函数内的代码进行了一些修改，导致最终产生了错误的 MerkelRoot ？

根据图片内的信息，我们进行了这些判断。如果上述回答没能解决你的问题，你可以提供更多信息给我们。
